### ISSUE TITLE
JobFlow/FlowPartのテストケース作成ウィザードでシート名が修正できない

### ISSUE THREAD

**Issue by cocoatomo** [hishidama/xtext-dmdl-editor#50]
デフォルトの名前としてポート名が使われているように見えるが, 31文字より多い長いポート名を使っていた場合, エラーが出るもののウィザードでは修正ができない.
そのためそれ以上ウィザードを進められない状態になってしまう.

**Comment by hishidama** [comment]
シート名がエラーになっている行をダブルクリックする（または行を選択してeditボタンを押す）と編集ダイアログが開き、そこでシート名を変更することが出来ます。

**Comment by cocoatomo** [comment]
エラーが出ている箇所を勘違いしていました。
