### ISSUE TITLE
FlowPartの修正でエラー

### ISSUE THREAD

**Issue by cocoatomo** [hishidama/xtext-dmdl-editor#51]
次の画像のようなエラーが出て, FlowPartの修正が完了しない.

![screen shot 2017-05-18 at 20 09 22](https://cloud.githubusercontent.com/assets/223050/26199743/2290d9e8-3c06-11e7-90dd-eb206439e030.png)

このFlowPartのクラス宣言行は次の通りで, この上限付き型バラメータ指定の部分が関係してるように見える.

```java
@FlowPart
public class ConstructActualFlowPart<M extends ProjKeyPeriodBudgetcode & ProjRowType & ProjMonthValues>
        extends FlowDescription {
```

**Comment by hishidama** [comment]
P1 & P2 のように2つ以上の型が定義されている場合にこのエラーが発生します。
